export const DEMO_RESULT = {
  id: "preview_great_wall",
  createdAt: "2026-07-15T08:00:00.000Z",
  mode: "preview",
  inputKind: "text",
  claim: "The Great Wall of China is visible from the Moon with the naked eye.",
  verdict: "refuted",
  truthScore: 9,
  confidence: 93,
  summary:
    "The claim is refuted. Astronaut observations and space-imaging references agree that the Great Wall is generally not visible from the Moon unaided and is difficult to distinguish even from low Earth orbit.",
  scoring: {
    modelConsensus: 4,
    evidenceBalance: 8,
    sourceCoverage: 100,
    modelAgreement: 98,
    formula: "55% model consensus + 45% source-weighted evidence; weak evidence is pulled toward 50.",
  },
  sources: [
    {
      id: "preview-1",
      title: "China's Wall Less Great in View from Space",
      url: "https://science.nasa.gov/earth/earth-observatory/chinas-wall-less-great-in-view-from-space-6225/",
      publisher: "NASA Earth Observatory",
      publisherUrl: "https://science.nasa.gov",
      publishedAt: "2005-05-09T00:00:00.000Z",
      snippet: "NASA explains that the wall is difficult or impossible to see from low Earth orbit without magnification and is not visible from the Moon.",
      origin: "Preview fixture",
      stance: "refute",
      reliability: 98,
      reason: "Direct space-observation authority addressing the exact visibility claim.",
    },
    {
      id: "preview-2",
      title: "Is the Great Wall of China Visible from the Moon?",
      url: "https://www.britannica.com/story/is-the-great-wall-of-china-visible-from-the-moon",
      publisher: "Encyclopaedia Britannica",
      publisherUrl: "https://www.britannica.com",
      publishedAt: null,
      snippet: "Britannica traces the myth and explains why the structure cannot be seen from the Moon with the naked eye.",
      origin: "Preview fixture",
      stance: "refute",
      reliability: 91,
      reason: "Independent reference work that directly evaluates the myth.",
    },
    {
      id: "preview-3",
      title: "Great Wall from space",
      url: "https://www.esa.int/ESA_Multimedia/Images/2004/05/Great_Wall_from_space",
      publisher: "European Space Agency",
      publisherUrl: "https://www.esa.int",
      publishedAt: "2004-05-11T00:00:00.000Z",
      snippet: "ESA imagery illustrates the difficulty of locating the Great Wall even in detailed satellite images.",
      origin: "Preview fixture",
      stance: "refute",
      reliability: 96,
      reason: "Independent space agency evidence consistent with NASA's account.",
    },
  ],
  models: [
    {
      role: "Investigator",
      model: "moonshotai/Kimi-K2.6",
      requestId: null,
      durationMs: null,
      usage: { inputTokens: 0, outputTokens: 0 },
      verdict: "refuted",
      confidence: 96,
      summary: "Multiple independent space agencies directly contradict the naked-eye visibility claim.",
      reasoning: [
        "The claim specifies observation from the Moon, a much greater distance than low Earth orbit.",
        "NASA and ESA evidence both describe the wall as difficult to distinguish even from closer orbital distances.",
        "No direct observational evidence supports the viral claim.",
      ],
      missingEvidence: [],
      evidenceAssessments: [],
    },
    {
      role: "Skeptic",
      model: "MiniMaxAI/MiniMax-M2.7",
      requestId: null,
      durationMs: null,
      usage: { inputTokens: 0, outputTokens: 0 },
      verdict: "refuted",
      confidence: 94,
      summary: "The myth likely confuses occasional visibility from low orbit using imaging equipment with unaided visibility from the Moon.",
      reasoning: [
        "Visibility depends on contrast and angular resolution, not simply the wall's length.",
        "A photographed feature from orbit does not establish naked-eye visibility from lunar distance.",
        "The cited authorities are independent and converge on the same conclusion.",
      ],
      missingEvidence: [],
      evidenceAssessments: [],
    },
  ],
  missingEvidence: [],
  trace: [
    {
      stage: "evidence-retrieval",
      provider: "Preview fixture",
      model: null,
      requestId: null,
      startedAt: null,
      durationMs: null,
      status: "preview",
    },
    {
      stage: "investigator-analysis",
      provider: "GonkaRouter",
      model: "moonshotai/Kimi-K2.6",
      requestId: null,
      startedAt: null,
      durationMs: null,
      status: "preview",
    },
    {
      stage: "skeptic-cross-check",
      provider: "GonkaRouter",
      model: "MiniMaxAI/MiniMax-M2.7",
      requestId: null,
      startedAt: null,
      durationMs: null,
      status: "preview",
    },
  ],
};
